### ISSUE TITLE
Install with Zig Fetch

### ISSUE THREAD

**Issue by dotfelixb** [mitchellh/libxev#103]
What is the url for libxev to install using
```
zig fetch --save '<libxev url>'
```

**Comment by kassane** [comment]
> What is the url for libxev to install using
> ```
> zig fetch --save '<libxev url>'
> ```

Hi @dotfelixb 

Try:
```bash
# write or overwrite on zon dependencies
zig fetch --save=libxev git+https://github.com/mitchellh/libxev
```

In version 0.13.0 you do not need to add the commit hash (or branch name) to the URL as it will already be linked. However, previous versions need to add git+url#commit-hash
