### ISSUE TITLE
Build failure on Zig master

### ISSUE THREAD

**Issue by mnemnion** [mitchellh/libxev#108]
Caused by [this line](https://github.com/mitchellh/libxev/blob/43c7e4b3308f359e5b758db2d824d7c447f4ed3f/build.zig#L208), which uses `@src()` [here](https://github.com/mitchellh/libxev/blob/43c7e4b3308f359e5b758db2d824d7c447f4ed3f/build.zig#L346) to get the current file path. 

`@src()` no longer includes the full path with `.file`. There's a `.module` field, but not yet any way to combine those and get a file handle, this is being tracked as [#20999](https://github.com/ziglang/zig/issues/20999#issuecomment-2278780647) on the Zig issue board.

**Comment by mitchellh** [comment]
I need to update the README, but we only pin to released versions now.

**Comment by mnemnion** [comment]
Suits me. I wanted to create a link trail, because it's unlikely that the change to `@src()` will be reverted, and the necessary changes for `libxev` to build on the next release will be showing up at the linked issue.

**Comment by mnemnion** [comment]
Would this not make sense to keep open as a tracking issue for that change?

**Comment by mnemnion** [comment]
Sure. Changing the documentation so it doesn't say Zig nightly would make sense then, but it doesn't need to be tagged as a bug, just a tracking issue for a change which is needed at some future point.
