### ISSUE TITLE
Serialized writes 

### ISSUE THREAD

**Issue by mitchellh** [mitchellh/libxev#11]
RIght now, if multiple writes are submitted, all writes happen in any possible order (i.e. io_uring makes no guarantee about write order). Therefore, program authors must be careful to only submit the next write when the previous write callback succeeds. This may or may not be easy to do for program authors.

The recommendation for now is that program authors maintain their own queue, and use the write callback as a way to automatically rearm with the next queued item. 

We may want to consider introducing a higher level abstraction concept of serialized writes, where the completion and write queue is managed by this abstraction. I think it makes sense for the lower level loop to remain unaware of the write queue.

**Comment by judofyr** [comment]
A tiny note: I think io_uring's [linked requests](https://unixism.net/loti/tutorial/link_liburing.html) could be used for this. This requires the requests to be submitted together though. Also: Isn't this need also solved by `writev`?
